---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: lts/*

cache: yarn

script:
  - yarn lint
  - yarn run build


before_deploy:
  - '
    git config user.name "Deployment Bot (from Travis CI)" &&
    git config user.email "deploy@travis-ci.org"
    '
deploy:
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  target-branch: master
  on:
    branch: boss
